apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPServiceUsageConstraintV1
metadata:
  name: allow_basic_set_of_apis
  annotations:
    description: Only a basic set of APIS
    bundles.validator.forsetisecurity.org/healthcare-baseline-v1: security
spec:
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - "organizations/**"
    exclude: []
  parameters:
    mode: allow
    services:
    - "compute.googleapis.com"
