apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPAlwaysViolatesConstraintV1
metadata:
  name: always_violates_all
  annotations:
    description: Testing policy, will always violate.
spec:
  constraintVersion: 0.1.0
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - "organization/104924712991/folders/788633752998/*"
  parameters: {}
