apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPServiceUsageConstraintV1
metadata:
  name: deny_some_apis
  annotations:
    description: Deny a set of APIS
spec:
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - "organization/104924712991/*"
    - "organization/104924712991/folders/788633752998/*"
    exclude: []
  parameters:
    mode: deny
    services:
    - "container.googleapis.com"
    - "bigquery.googleapis.com"
    - "storage.googleapis.com"
