apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPServiceUsageConstraintV1
metadata:
  name: deny_some_apis
  annotations:
    description: Deny a set of APIS
spec:
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - "organization/104924712991/projects/628414193824/*"      
    exclude: []
  parameters:
    mode: deny
    services:
    - cloudapis.googleapis.com
    - iam.googleapis.com
